
---
services:
  immortalwrt:
    image: immortalwrt
    dns:
       - 192.168.31.1
    container_name: immortalwrt
    restart: always
    privileged: true
    networks:
      my_macvlan_network:
        ipv4_address: 192.168.31.100
    volumes:
      - /home/Xiaotong/Programs:/Programs
    command: /Programs/ImmortalWrtDocker/start_immortalwrt.sh

networks:
  my_macvlan_network:
    external: true
